### ISSUE TITLE
playbin not found, what player is being used?

### ISSUE THREAD

**Issue by Muriukidavid** [tuxmouraille/gSpeech#2]
File "./gSpeech.py", line 409, in onExecute
    player = self.onPlayer(SPEECH)
  File "./gSpeech.py", line 418, in onPlayer
    self.player = gst.element_factory_make("playbin", "player")
gst.ElementNotFoundError: playbin

**Comment by tuxmouraille** [comment]
Hello,

gSpeech is the player. It use python gstreamer. Did you install all the dependences?

python (>=2.7) python-gst0.10 (>=0.10) python-gtk2 (>=2.24) libttspico-utils (>= 1.0) python-notify (>=0.1) gstreamer0.10-plugins-base gstreamer0.10-plugins-good gstreamer0.10-pulseaudio

gSpeech only works with python 2.7,  GTK+ 2 and gstreamer 0.10.

**Comment by Muriukidavid** [comment]
Thanks, had not installed: gstreamer0.10-plugins-base gstreamer0.10-plugins-good gstreamer0.10-pulseaudio
